steps:
- id: 'Run apigeecli commands'
  name: ghcr.io/apigee/apigeecli:latest
  entrypoint: 'sh'
  args:
    - -c
    - |
      #setup preferences
      apigeecli prefs set --nocheck=true -o interno-ipnet-dev
      apigeecli token cache --metadata-token

      # openapi deployment #2
      apigeecli apis create bundle  -f buscaCep-vs_rev80_2024_01_12/apiproxy  -n buscaCep-vs
      apigeecli apis deploy -n buscaCep-vs -e defaultd-dev -r